### ISSUE TITLE
SyntaxError: invalid syntax Python 2.6.6

### ISSUE THREAD

**Issue by patsevanton** [b1naryth1ef/piera#19]
```
Python 2.6.6 (r266:84292, Jan 22 2014, 01:49:05) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import piera
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/piera/__init__.py", line 1, in <module>
    from .piera import *
  File "/usr/lib/python2.6/site-packages/piera/piera.py", line 314
    new_context = {k: v for k, v in new_context.items() if v}
                          ^
SyntaxError: invalid syntax
>>> 
```

**Comment by b1naryth1ef** [comment]
Supporting 2.6 isn't a big priority for me, if you'd like to contribute I'd be happy to merge if it doesn't massively impact the code quality/clarity. If not I'll probably need to drop the 2.6 classifier from the PyPi listing.

**Comment by patsevanton** [comment]
May be add requirements to readme.md?
